# Multiple Random Variables

Most often, we are interested in more than a single random variable. We may be interested in multiple observations that come from the same underlying population, and/or we can focus on random variables being drawn from different populations which may or may not be related to each other.

## Bivariate Probability Distributions

**Recall**: A (univariate) random variable is defined to be a function from a sample space $\cal{S}$ into the real numbers, $\mathbb{R}$. Often we are interested simultaneously in two outcomes of a random experiment rather than one. For example, we might be interested in \dots

-   SAT score and GPA for a student
-   Number of customers waiting in two lines at the grocery store
-   Number of hours spent studying and test score
-   Dosage of a drug and blood pressure

In each of these examples, there are two random variables, and we are interested in the 2-dimensional random vector $(X, Y)$. The concepts of discrete/continuous random variables, independence, CDFs and pmfs/pdfs can be extended to **bivariate random variables**, as well as $n$-dimensional random variables.

::: callout-tip
## Definition: Bivariate CDF

Let $X$ and $Y$ be two random variables. The joint cumulative distribution function (**bivariate CDF**) of $X$ and $Y$ is\
$$
F_{XY}(x,y) = \hbox{\hspace{110mm}}
$$\
\
:::

**Recall**: What are the conditions for a univariate CDF?

\
\

\newpage

::: callout-tip
## Theorem

The function $F_{XY}(x,y)$ is a bivariate CDF if and only if the following conditions hold:\
\
1.

\
2.

\
3.

\
\
4.

\
\
:::

**Recall**: How do we use a univariate pdf to find a univariate CDF?

::: callout-tip
## Definition: Joint pdf

If $X$ and $Y$ are jointly distributed/bivariate (absolutely) continuous random variables, then\
\
\
$F_{XY}(x,y) =$\
\
\
where $f_{XY}(x,y)$ is a **joint (bivariate) probability density function**, or joint pdf.
:::

**Recall**: How do we use a univariate pmf to find a univariate CDF?

::: callout-tip
## Definition: Joint pmf

If $X$ and $Y$ are jointly distributed/bivariate discrete random variables, then\
\
\
$F_{XY}(x,y) =$\
\
\
\
where $f_{XY}(x,y)$ is a **joint (bivariate) probability mass function**, or joint pmf.
:::

\newpage

**Recall**: How do we use a univariate CDF to find a univariate pdf?

::: callout-tip
## Relationship between Bivariate CDFs and pdfs

Bivariate CDFs and pdfs have the following relationship:\
\
\
\
\
\
\
\
$f_Y(Y)= \hbox{\hspace{60mm}} \hbox{and} \hbox{\hspace{5mm}} f_X(X)=$
\
\
That is, if we integrate one of the continuous random variables out of the bivariate/joint pdf, we are left with the pdf of the other variable. This is the **marginal probability density function of** $Y$. Similarly, we can get the **marginal probability mass function** of a discrete random variable by summing the other random variable out of the bivariate/joint pmf.
:::

**Recall**: If two events are independent, how do we find the probability of both events occurring?

\
\

::: callout-tip
## Theorem: Independence

Two random variables, $X$ and $Y$, are independent if and only if

-   **Using the CDF**:\
    \
    $F_{XY}(x,y) =$\
    \
    \

-   **Using the pdf/pmf**:\
    \
    $f_{XY}(x,y) =$\
    \

for every pair of real numbers $(x,y)$. Be careful with the support!
:::

\newpage

All of these definitions/theorems build upon what we've already learned. Now we'll try them out!

**Example**: Consider the function $F_{XY}(x,y) = \frac{1}{16}xy(x+y)$, $0 \leq x \leq 2$, $0 \leq y \leq 2$.

-   Verify that $F_{XY}(x,y)$ is a CDF.

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

-   Find the corresponding joint pdf and verify it is a pdf.

\
\
\
\
\
\
\
\
\
\
\

-   Are $X$ and $Y$ independent?

\
\
\

\newpage

-   Find $P(0 \leq X \leq 1, 0 \leq Y \leq 1)$

\
\
\
\
\
\
\
\
\
\
\
\

**Example**: Points are uniformly (and randomly) distributed in the unit square. That is, $X \sim$ Uniform(0,1) and $Y \sim$ Uniform(0,1). Assume $X$ and $Y$ are independent.

-   What are the univariate pdfs for $X$ and $Y$?

\
\
\

-   What is the joint pdf of $X$ and $Y$?

\
\
\

-   Find $P(Y < X)$.

\
\
\

\newpage

**Example**: Let $X$ and $Y$ have a joint density function given by $f_{XY}(x,y) = \left\{\begin{array}{ll} kx & 0 \leq y \leq x \leq 1 \\ 0 & \hbox{elsewhere} \end{array} \right.$ .

-   Find $k$. Are $X$ and $Y$ independent?

\
\
\

-   Find the marginal density functions (pdfs) of $X$ and $Y$.

\
\
\
\
\
\
\
\

-   Find the joint CDF of $X$ and $Y$.

\
\
\

\newpage

**Example**: Let $X$ and $Y$ have joint pdf given by

$f_{XY}(x,y) = \left\{\begin{array}{ll} kxy & 0 \leq x \leq 1, 0 \leq y \leq 1 \\  0 & \hbox{elsewhere} \end{array} \right.$.

-   Find $k$.

\
\
\
\
\
\
\

-   Find the joint CDF of $X$ and $Y$.

\
\
\
\
\

\newpage

**Example**: A juice company produces blends of juices with each blend containing various proportions of cranberry, grape and other juices. The proportions of cranberry and grape juice in a blend are random variables with joint pdf ($X$ = cranberry and $Y$ = grape): $$
f_{XY}(x,y) = \left\{\begin{array}{ll} 24xy & 0 \leq x \leq 1, 0 \leq y \leq 1, x+y \leq 1 \\ 0 & \hbox{elsewhere} \end{array} \right. .
$$

-   Find the probability that in a given bottle, the cranberry juice accounts for over half the blend.

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

-   Find the marginal density function for the proportion of grape juice.

\
\
\

\newpage

## Bivariate Expectations

Similar to the univariate case, we can also find the expected value of functions of multiple random variables.

::: callout-tip
## Definition: Bivariate Expectations

Suppose $g(x,y)$ is a real-valued function. If $X$ and $Y$ are random variables with joint pmf/pdf $f_{XY}(x,y)$, then\
\
\
\
\
E$[g(X,Y)] =$\
\
\
\
\
\
:::

**Example**: Consider the joint pdf $f_{XY}(x,y) = \left\{\begin{array}{ll} e^{-y} & 0 < x < y < \infty \\ 0 & \hbox{elsewhere} \end{array} \right.$. Find E$(X^2 Y)$.

\
\
\

\newpage

**Example**: Consider the joint pmf $$
f_{XY}(x,y) = \left\{\begin{array}{ll} {y \choose x} p^x(1-p)^{y-x} \frac{e^{-\lambda} \lambda^y}{y!} & y=0,1,2,\dots; x=0,\dots, y \\ 0 & \hbox{elsewhere} \end{array} \right. .
$$

-   What does the support look like?

\
\
\
\
\
\
\

-   Find the marginal pmf of $Y$.

\
\
\
\
\
\
\

-   Find the marginal pmf of $X$.

\
\
\

\newpage

-   Find E$(XY)$.

\
\
\
\
\
\
\
\
\
\
\
\
\
\

## Independence

Independence can make our lives easier in lots of ways!

::: callout-tip
## Theorem

If two random variables $X_1$ and $X_2$ are independent, then\
\
E$[g(X_1) h(X_2)] =$\
:::

However, we don't need the marginal CDFs and pmfs/pdfs to show independence! We can show independence using non-negative functions of the variables themselves.

::: callout-tip
## Theorem: Independence

Two random variables, $X$ and $Y$, are independent if and only if\
\
$f_{XY}(x,y) =$\
\
\
for all $x, y$ in $\mathbb{R}$.
:::

**Example**: Consider the joint pdf $f_{XY}(x,y) = \left\{\begin{array}{ll} 8xy & 0 < x < y < 1 \\ 0 & \hbox{elsewhere} \end{array} \right.$. Are $X$ and $Y$ independent?

\newpage

**Example**: Consider the joint pmf $f_{XY}(x,y) = \left\{\begin{array}{ll} e^{-4} \left ( \frac{2^{x+y}}{x! y!} \right ) & y=0,1,2,\dots; x=0,1,2,\dots \\ 0 & \hbox{elsewhere} \end{array} \right.$. Are $X$ and $Y$ independent?

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

**Example**: Consider the joint pdf $f_{XY}(x,y) = \left\{\begin{array}{ll} x+y & 0<x<1; 0<y<1 \\ 0 & \hbox{elsewhere} \end{array} \right.$. Are $X$ and $Y$ independent?

\
\
\

## Conditional Distributions

Often, two random variables are not independent. For example, a randomly selected person's height is typically related to his/her weight. If we looked at the conditional distribution of a randomly selected person's weight given that we knew a randomly selected person was 63 inches tall, it would be different from the distribution of any randomly selected person's weight. The additional information about height changes the distribution of weight, so these two random variables are not independent. In such cases, we are often interested in the conditional probability of $Y$ given knowledge that $X=x$. Recall the definition of conditional probability:

\newpage

This definition can be extended to conditional distributions.

::: callout-tip
## Definition: Conditional pmf/pdf

The conditional pdf or pmf of $Y$ given $X=x$ is\
\
$f_{Y|X}(y|x) =$\
\
\
:::

If $X$ and $Y$ are independent random variables, then

\
\
\
\
\

**Example**: Consider the joint pdf $f_{XY}(x,y) = \left\{\begin{array}{ll} e^{-y} & 0 < x < y < \infty \\ 0 & \hbox{elsewhere} \end{array} \right.$. We can show the marginal pdfs of $X$ and $Y$ (left as practice for you!) are: $$
f_X(x) = \left\{\begin{array}{ll} e^{-x} & 0 < x < \infty \\ 0 & \hbox{else} \end{array} \right .  \hbox{\hspace{5mm} and \hspace{5mm}} f_Y(y) = \left \{ \begin{array}{ll} ye^{-y} & 0 < y < \infty \\ 0 & \hbox{else} \end{array} \right. .
$$

-   For $x > 0$, find the conditional pdf of $Y|X$.

\
\
\
\
\
\
\

-   For $y > 0$, find the conditional pdf of $X|Y$.

\
\
\
\

\newpage

**Example**: Consider the joint pmf $$
f_{XY}(x,y) = \left\{\begin{array}{ll} {y \choose x} p^x(1-p)^{y-x} \frac{e^{-\lambda} \lambda^y}{y!} & y=0,1,2,\dots; x=0,\dots, y \\ 0 & \hbox{elsewhere} \end{array} \right. .
$$ Previously, we showed that $X\sim$ Poisson$(p\lambda)$ and $Y\sim$ Poisson$(\lambda)$.

-   For $x=0,1,2,\dots$, find the conditional pmf of $Y|X$.

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

-   For $y=0,1,2,\dots$, find the conditional pmf of $X|Y$.

\
\
\
\
\

\newpage

## Conditional Expectations

Conditional distributions can be used in the same way unconditional distributions are used. For example, conditional distributions may be used to compute conditional expectations.

::: callout-tip
## Definition: Conditional Expectation

If $X$ and $Y$ are two random variables and $g(Y)$ is a function of $Y$, then the **conditional expectation** of $g(Y)$ given $X=x$ is:\
\
\
\
E$[g(Y)|X=x] =$\
\
\
\
In particular, the **conditional mean** of $Y$ given $X=x$ is:\
\
\
\
E$(Y|X=x) =$\
\
\
\
and the **conditional variance** of $Y$ given $X=x$ is:

\
Var$(Y|X=x) =$\
\
\
\
\
:::

**Example**: Consider the joint pdf $f_{XY}(x,y)=\left\{\begin{array}{ll} e^{-y} & 0 < x < y < \infty \\ 0 & \hbox{elsewhere} \end{array} \right.$. Previously, we showed the conditional distribution of $X|Y$ is $f_{X|Y}(x|y) = \left\{\begin{array}{ll} \frac{1}{y} & 0 < x < y < \infty \\ 0 & \hbox{elsewhere} \end{array} \right.$.

-   Find E$(X|Y=y)$

\

\newpage

-   Find Var$(X|Y=y)$

\
\
\
\

Conditional expectations lend themselves to other useful results, such as finding the expected values and variances of univariate random variables.

::: callout-tip
## Theorem

If $X$ and $Y$ are two random variables, then
\
\
$\hbox{E}(Y)= \hbox{\hspace{60mm}} \hbox{and} \hbox{\hspace{5mm}} \hbox{E}(X)=$
:::

**Proof**:

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

**Example**: Consider the joint pdf $f_{XY}(x,y)=\left\{\begin{array}{ll} e^{-y} & 0 < x < y < \infty \\ 0 & \hbox{elsewhere} \end{array} \right.$. Previously, we showed E$(X|Y=y) =$ \hspace{15mm} and mentioned that $f_Y(y) = \left\{\begin{array}{ll} y e^{-y} & 0 < y < \infty \\ 0 & \hbox{elsewhere} \end{array} \right.$. What is E$(X)$?

\newpage

**Example**: Consider the joint pmf $$
f_{XY}(x,y) = \left\{\begin{array}{ll} {y \choose x} p^x(1-p)^{y-x} \frac{e^{-\lambda} \lambda^y}{y!} & y=0,1,2,\dots; x=0,\dots, y \\ 0 & \hbox{elsewhere} \end{array} \right. .
$$ Previously, we showed that $X\sim$ Poisson$(p\lambda)$, $Y\sim$ Poisson$(\lambda)$ and $X|Y\sim$ Binomial$(y,p)$. What is E$(X)$?

\
\

::: callout-tip
## Theorem

If $X$ and $Y$ are two random variables, then\
\
Var$(Y) =$\
\
:::

**Proof**:

-   We know E$(Y) =$ \hspace{30mm}. Similarly, E$(Y^2) =$\

-   By definition, we know Var$(Y|X) =$\

-   We also know E\[Var$(Y|X)$\] =\

-   By definition, Var\[E$(Y|X)$\] =\

-   Therefore, E\[Var$(Y|X)$\] + Var\[E$(Y|X)$\] =

\
\
\
\

\newpage

**Example**: Suppose the number of eggs laid by a certain insect has a Poisson distribution with mean $\lambda$. The probability that any one egg hatches is $p$. Assume the eggs hatch independently of one another.

*What do we know?*

\

1.  Find the expected value of $Y$, the total number of eggs that hatch.

\

2.  Find the variance of $Y$.

\
\
\

**Example**: In a clinical study of a new drug formulated to reduce the effects of rheumatoid arthritis, researchers found the proportion $p$ of patients who respond favorably to the new drug is a random variable that varies from batch to batch of the drug. Assume that $p$ has a probability density function given by $$
f(p) = \left\{\begin{array}{ll} 12p^2(1-p) & 0 \leq p \leq 1 \\ 0 & \hbox{elsewhere} \end{array} \right. .
$$ Suppose $n$ patients are injected with portions of the drug taken from the same batch. Let $Y$ denote the number showing a favorable response.

1.  Find the unconditional probability distribution of $Y$ for general $n$.

\
\
\
\
\
\
\
\
\
\
\
\
\

2.  Find E$(Y)$ for $n=2$.

\newpage

## Covariance and Correlation

If two random variables are not independent, we are often interested in finding their conditional distributions. However, we are often also interested in quantifying the strength of the relationship between them. For example, we could quantify the strength of the relationship between a randomly chosen person's height and weight or the strength of the relationship between a randomly chosen person's height and GPA. We would expect the relationship between a randomly chosen person's height and weight would be much stronger than that between a randomly chosen person's height and GPA. Covariance and correlation are two commonly used numerical measures of the strength of a relationship between two random variables.

::: callout-tip
## Theorem (Covariance)

Let $X$ and $Y$ be jointly distributed random variables such that E$(X) = \mu_X$, Var$(X) = \sigma^2_X$, E$(Y) = \mu_Y$, and Var$(Y) = \sigma^2_Y$. The **covariance** between $X$ and $Y$ is\
\
Cov$(X,Y) =$\
\
\
\
\
\
\
\
\
\
:::

**Note**: Cov$(X,Y)$ = Cov$(Y,X)$. What is Cov$(X,X)$?

\
\
\

::: callout-tip
## Theorem

If $X$ and $Y$ are independent random variables, then\
\
Cov$(X,Y) =$\
\
\

Thus, independent random variables must be uncorrelated. However, the converse is not true. That is, if the covariance between two random variables is zero, this does necessarily imply they are independent.
:::

\newpage

Covariance is useful when calculating the correlation between two random variables.

::: callout-tip
## Definition (Correlation)

Let $X$ and $Y$ be jointly distributed random variables such that Var$(X) = \sigma^2_X$ and Var$(Y) = \sigma^2_Y$. The **correlation** between $X$ and $Y$ is\
\
$\rho_{XY} = \hbox{Corr}(X,Y) =$\
\
\
\
:::

**Facts About the Correlation**:

1.  \

2.  \

Covariance is also useful when calculating the variance of linear functions of random variables.

::: callout-tip
## Theorem

If $X$ and $Y$ are jointly distributed random variables, then\
\
E$(aX + bY) =$\
\
Var$(aX + bY) =$\
\
If $X$ and $Y$ are **independent** random variables, then\
\
Var$(aX + bY) =$\
\
:::

**Proof**: Suppose $X$ and $Y$ are jointly distributed random variables such that E$(X) = \mu_X$ and E$(Y) = \mu_Y$.

Var$(aX + bY) =$

\
\
\

\newpage

**Example**: Consider the joint pmf $$
f_{XY}(x,y) = \left\{\begin{array}{ll} {y \choose x} p^x(1-p)^{y-x} \frac{e^{-\lambda} \lambda^y}{y!} & y=0,1,2,\dots; x=0,\dots, y \\ 0 & \hbox{elsewhere} \end{array} \right. .
$$ Previously, we showed that $X\sim$ Poisson$(p\lambda)$, $Y\sim$ Poisson$(\lambda)$ and E$(XY) = p\lambda + p\lambda^2$.

-   Find Corr$(X,Y)$.

\
\
\
\
\
\
\
\
\
\

-   Find Var$(3X-4Y)$.

\
\
\
\

\newpage

## Multivariate Probability Distributions

**Recall**: A (univariate) random variable is a function from a sample space $\cal{S}$ into the real numbers, $\mathbb{R}$. In the bivariate case, we are interested in a 2-dimensional random vector $(X,Y)$, that is, a function from a sample space $\cal{S}$ into $\mathbb{R}^2$. We can also consider $n$-dimensional random vectors, or random vectors with more than two random variables.

::: callout-tip
## Definition: $n$-Dimensional Random Vector

An $n$-dimensional random vector is\
\
\
:::

As before, the concepts of discrete/continuous random variables, independence, CDFs and pmfs/pdfs that were extended to bivariate random variables can also be extended to $n$-dimensional random vectors.

::: callout-tip
## Definition: Multivariate CDF

Let $X_1, X_2,\dots,X_n$ be $n$ random variables. The multivariate cumulative distribution function (**multivariate CDF**) of $X_1,X_2,\dots, X_n$ is\
\
$F(x_1,\dots,x_n) =$\
\
:::

::: callout-tip
## Definition: Multivariate pdf

If $(X_1,\dots,X_n)$ are (absolutely) continuous, then\
\
$F(x_1,\dots,x_n) =$\
\
\
where $f(x_1,\dots, x_n)$ is a **multivariate probability density function**, or multivariate pdf.
:::

::: callout-tip
## Definition: Multivariate pmf

If $(X_1,\dots,X_n)$ are discrete, then\
\
$F(x_1,\dots,x_n) =$\
\
\
\
where $f(x_1,\dots, x_n)$ is a **multivariate probability mass function**, or multivariate pmf.
:::

\newpage

::: callout-tip
## Relationship between Multivariate CDFs and pdfs

Continuous multivariate CDFs and pdfs have the following relationship:\
\
\
\
:::

::: callout-tip
## Definition: Marginal Distributions

If $(X_1,\dots,X_n)$ are (absolutely) continuous, then

-   the **marginal CDF** of the random variable $X_j$ is\
    \
    $F_{X_j}(x_j) =$\
    \
    \
    \
    \
    \
    \
    \
    \

-   and the **marginal pdf** of the random variable $X_j$ is\
    \
    $f_{X_j}(x_j) =$\
    \
    \
    \
    \
    \
    \
    \
    \
    \

That is, if we integrate $k$ ($k < n$) continuous random variables out of the multivariate pdf, we are left with the marginal pdf of the other $n-k$ variable(s). Similarly, we can get the **marginal probability mass function** of a discrete random variable by summing the other random variables out of the multivariate pmf.
:::

\newpage

**Example**: Let $X_1,X_2,X_3,X_4$ be continuous random variables with joint cdf $F(x_1,x_2,x_3,x_4)$ and joint pdf $f(x_1,x_2,x_3,x_4)$.

-   What is the marginal CDF of $X_2$?

\
\
\

-   What is the marginal pdf of $X_2$?

\
\
\

**Example**: Let $X_1, X_2, X_3$ be continuous random variables with joint pdf $$f(x_1,x_2,x_3) = \left\{\begin{array}{ll} c & 0 < x_1 < x_2 < x_3 < 1 \\ 0 & \hbox{elsewhere} \end{array} \right. .$$

-   Find $c$.

\
\
\
\
\
\

-   What is the marginal pdf of $X_3$?

\
\
\
\
\
\

-   Find $f_{X_1 X_2}(x_1,x_2)$.

\
\
\

\newpage

### Multivariate Expectations

Similar to the univariate case, we can also find the expected value of a function of multiple random variables.

::: callout-tip
## Definition: Multivariate Expectation

Suppose $g(x_1,\dots,x_n)$ is a real-valued function. If $X_1,\dots, X_n$ are continuous random variables with joint pdf $f(x_1,\dots,x_n)$ then\
\
E$[g(X_1,\dots,X_n)] =$\
\
:::

**Example**: Let $X_1,X_2,X_3$ be continuous random variables with joint pdf $$f(x_1,x_2,x_3) = \left\{\begin{array}{ll} c & 0 < x_1 < x_2 < x_3 < 1 \\ 0 & \hbox{elsewhere} \end{array} \right. .$$ Find E$(X_1 X_2 X_3)$.

\
\
\
\
\

### Multivariate Independence

The concept of independence can also be extended from the bivariate case to the multivariate case.

::: callout-tip
## Definition: Mutual Independence

$X_1,\dots, X_n$ are mutually independent if and only if

-   **Using the CDF**:

$F(x_1,\dots, x_n) =$

-   **Using the pdf/pmf**:

$f(x_1,\dots,x_n) =$

\

for all $(x_1,\dots, x_n)$ in $\mathbb{R}$.
:::

\newpage

If random variables are independent, a useful result follows.

::: callout-tip
## Theorem

If $X$ and $Y$ are independent random variables, then\
Var$(aX+bY) =$\
\
In general: If $X_1,\dots, X_n$ are mutually independent random variables with Var$(X_i) = \sigma^2_i$, $i=1,\dots,n$, then\
\
Var$\left(\sum_{i=1}^n a_i X_i \right) = \sum_{i=1}^n a_i^2 \sigma^2_i$\
:::

### Multivariate Conditional Distributions

The definition of conditional pdfs and conditional pmfs can also be extended to more than two dimensions.

::: callout-tip
## Definition: Higher Dimensionall pdf/pmf

Let $X_1,\dots, X_n$ be absolutely continuous/discrete random variables. Then, the following conditional pdfs/pmfs are defined as:\
\
\
$f_{X_1|X_2,\dots, X_n}(x_1|x_2,\dots, x_n) =$\
\
\
\
$f_{X_1 X_2|X_3,\dots,X_n}(x_1,x_2|x_3,\dots,x_n) =$\
\
\
\
:::

\newpage

**Example**: Let $X_1,X_2,X_3$ be continuous random variables with joint pdf $$f(x_1,x_2,x_3) = \left\{\begin{array}{ll} c & 0 < x_1 < x_2 < x_3 < 1 \\ 0 & \hbox{elsewhere} \end{array} \right. .$$ Previously, we found $$
f_{X_3}(x_3) = \left\{\begin{array}{ll} 3x_3^2 & 0 < x_3 < 1 \\ 0 & \hbox{elsewhere} \end{array} \right. \hbox{\hspace{5mm} and \hspace{5mm}} f_{X_1 X_2}(x_1,x_2) = \left\{\begin{array}{ll} 6 - 6x_2 & 0 < x_1 < x_2 < 1 \\ 0 & \hbox{elsewhere} \end{array} \right.
$$

-   Find the conditional pdf $f_{X_1 X_2|X_3}(x_1,x_2|x_3)$.

\
\
\
\

-   Find the conditional pdf $f_{X_3|X_1 X_2}(x_3|x_1,x_2)$.

\
\
\
\
\
\

## Multivariate Families of Distributions

There are named multivariate families of distributions, just as there are univariate families of distributions. We are only going to talk about two: one discrete (multinomial) and one continuous (bivariate normal)

\newpage

### The Multinomial Distribution

::: callout-tip
## Multinomial Distribution

**When it is used?** To model scenarios in which independent trials result in more than two possible outcomes. Multinomial experiments are generalizations of binomial experiments. The multinomial distribution is characterized by:

1.  The experiment consists of $n$ identical trials

2.  The outcome of each trial falls into one of $k$ classes

3.  The probability the outcome of a single trial falls in class $i$ is $p_i$, $i=1,\dots,k$ and remains constant over trials\

4.  Trials are independent

5.  The random variables of interest are $Y_1,Y_2,\dots,Y_k$ where $Y_i=$ the number of trials within class $i$

\
\

**pmf**: $f_{Y_1,\dots,Y_k}(y_1,\dots,y_k;n,p_1,\dots,p_k) = \left\{\begin{array}{ll} \hbox{\hspace{50mm}} & y_i=0,1,2,\dots,n \\ &  y_1+\cdots+y_k = n \\  & i=1,\dots,k\\  & \\ &  \\ 0 & \hbox{otherwise} \end{array} \right.$

**Expected Value}**: E$(Y_i) =$\

**Variance**: Var$(Y_i) =$\

**Covariance**: Cov$(Y_i, Y_j) =$
:::

**Example**: The National Fire Incident Reporting Service stated that, among residential fires, 73% are in family homes, 20% are in apartments, and 7% are in other types of dwellings. If four residential fires are independently reported on a single day, what is the probability that two are in family homes, one is in an apartment, and one is another type of dwelling?

\newpage

### The Bivariate Normal Distribution

The multivariate normal distribution is the foundation for most modern statistical theory. In general, the multivariate normal distribution is defined for $n$ continuous random variables, $X_1,X_2,\dots, X_n$. Because of its complexity, we look only at the **bivariate normal** distribution (at least until the next chapter!).

::: callout-tip
## Definition: Bivariate Normal Distribution

$(X,Y)$ has a bivariate normal distribution if its probability density function has the form\
\
\
\
$f_{XY}(x,y) =$\
\
\
\

We denote this as $(X,Y) \sim N_2(\mu_X,\mu_Y,\sigma^2_X,\sigma^2_Y,\rho_{XY})$.
:::

**Properties of the Bivariate Normal Distribution**:

1.  $X$ and $Y$ both have

\
\
\
\
\
\
\

2.  $Y|X=x \sim$

\
\
\
\
\

3.  $\rho_{XY}$

\

\newpage

**Proof**: Show $\rho_{XY}$ is the correlation coefficient between $X$ and $Y$.

-   Cov$(X,Y)$ =

\

-   E$(XY) =$

\
\
\
\
\
\

-   Corr$(X,Y) =$

\
\
\

**Independence**

-   We know if $X$ and $Y$ are independent, then $\rho_{XY} =$

-   Let $X$ and $Y$ be bivariate normally distributed RVs. What happens if $\rho_{XY}=0$? What does the bivariate normal pdf reduce to? What does this imply?

\
\
\
\
\
\
\
\
\
\

::: callout-tip
## Independence of Bivariate Normal Random Variables

Let $X$ and $Y$ be bivariate normally distributed random variables. $X$ and $Y$ are independent if and only if $\rho_{XY}=0$.\
:::
