---
project:
  output-dir: docs
  
format: 
  html: default
  pdf:   
    header-includes:
        - \usepackage{float}
        - \floatplacement{table}{H}  
    fontsize: 11pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm
---

# **STAT 262: Probability for Statisticians**

**Instructor:** Dr. Erin Blankenship (she/her)

**email:** `erin.blankenship@unl.edu`

**Lecture:** 2:00-3:15 Tuesday/Thursday, Plant Science 272

**Office Hours:** 9:30-11:00 Tuesday/Thursday or by appointment; 343B Hardin Hall, North Wing

**Required Materials:** There is no required textbook for this course.

**Reference:** *Mathematical Statistics with Applications*, 7th edition (Wackerly, Mendenhall and Scheaffer; 2008)

**Prerequisites:** MATH 208 (Calculus III), or the equivalent

**Course Description:** Probabilistic undergirding of statistical procedures including moments, common parametric families, marginal and conditional densities, sufficient statistics, modes of convergence, laws of large numbers, and the central limit theorem and how they apply to estimators.

**Course Goals:**

-   Understand and be able to apply the basic rules of probability, including sample spaces, conditional probability, independence, and Bayes' theorem

-   Understand and be able to articulate the definition of random variable for a specific scenario

-   Recognize and be able to use the different function associated with random variables: cumulative distribution function, probability density/mass function, moment generating function

-   Use density/mass functions to find moments

-   Use common discrete and continuous probability distributions to model real-world scenarios

-   Understand and be able to use multivariate probability distributions, including marginal and conditional distributions, independence, and covariance between random variables

-   Derive and use probability distributions of functions of random variables using the methods of transformations, Jacobians, and moment generating functions

-   Understand and be able to recognize random samples, including random samples drawn from the normal distribution

-   Understand and be able to recognize the distribution of functions of normal random variables

-   Understand elementary convergence concepts, including the law of large numbers and the Central Limit Theorem

\newpage

**Grading:**

| Assignment(s)      | Contribution to Final Grade |
|--------------------|-----------------------------|
| Exam 1             | 20%                         |
| Exam 2             | 20%                         |
| Homework           | 25%                         |
| Writing Assignment | 10%                         |
| Final Project      | 25%                         |

\

**Grading Scale:**

| Grade | Final Percentage Range |
|-------|------------------------|
| A     | 94.0-100               |
| A-    | 90.0-93.99             |
| B+    | 88.0-89.99             |
| B     | 84.0-87.99             |
| B-    | 80.0-83.99             |
| C+    | 78.0-79.99             |
| C     | 74.0-77.99             |
| C-    | 70.0-73.99             |
| D+    | 68.0-69.99             |
| D     | 64.0-67.99             |
| D-    | 60.0-63.99             |
| F     | \<60.0                 |

\
**Course Expectations:** In this course, you are expected to have professional behavior. You are expected to attend all class meetings, be curious, ask questions, seek opportunities to learn, and be open and responsive to constructive feedback. In addition:

-   Be an active participant--statistics is not a spectator sport!

-   Be committed, take your work seriously

-   Engage with the in-class activities and labs

-   Help others--if you understand the material being discussed, practice your mentoring skills. This does not means sharing answers, but instead helping others understand the concepts.

-   Complete any assigned readings.

You are also expected to exhibit a professional demeanor (language, attitude) toward others. Disagreement during discussions is welcome and often productive in developing a deeper understanding of the concepts being discussed. However, disagreement does not warrant yelling or disrespectful language or behavior. Unprofessional behavior will not be tolerated, and appropriate actions will be taken to prevent future occurrences.

**Recording of class-related activity:** I invite all of you to join me in actively creating and contributing to a positive, productive, and respectful classroom culture. Each student contributes to an environment that shapes the learning process. Any work and/or communication that you are privy to as a member of this course should be treated as the intellectual property of the speaker/creator, and is not to be shared outside the context of this course.

Students may not make or distribute screen captures, audio/video recordings of, or livestream, any class-related activity, including lectures and presentations, without express prior written consent from me or an approved accommodation from Services for Students with Disabilities. If you have (or think you may have) a disability such that you need to record or tape class-related activities, you should contact Services for Students with Disabilities. If you have an accommodation to record class-related activities, those recordings may not be shared with any other student, whether in this course or not, or with any other person or on any other platform.

**Homework:** Approximately 8-10 homework assignments will be made over the course of the semester. The only way to learn statistics is to practice working problems, and homework is therefore an essential part of the course. Bear in mind that homework is for your benefit, not the instructor's.

Homework may be submitted either on paper or through Canvas. If you opt to submit via Canvas, it must be submitted as a single pdf (not multiple files), and any scans must be high quality. If I cannot read it, it will not be graded. Homework will be graded partially on completeness and partially on accuracy.

**Calculators:** We will be using a great deal of calculus in this course. While I realize that many calculators will do the calculus we'll use, such calculators will **not** be permitted on in-class exams. Don't get too reliant on them for homework!

**Writing Assignment:** Written communication is an essential part of any job. To help you get used to writing about statistics, as well as to reinforce and assess understanding of class concepts, you will assigned a formal writing project. More details on the writing assignment will be distributed later.

**Exams:** Two exams will be given during the course of the semester, tentatively scheduled on , and . The in-class exams are closed book and notes. The exams will evaluate your understanding of the material, as well as your ability to synthesize and transfer that knowledge to other scenarios and situations; questions will assess conceptual understanding as opposed to mere memorization.

**Final Project:** In lieu of a final exam, there will be a project assignment to allow you demonstrate your understanding and synthesis of the course concepts. More details on the project will be distributed later.

**Instructional Continuity:** If in-person classes are canceled, you will be notified of the instructional continuity plan for this class through Canvas.

\newpage

**AI and Explainability Policy:** (adapted from Dr. Vanderplas)

-   Any use of generative AI must be disclosed in an appendix to your submission - this includes brainstorming, editing, using AI as spell-check/grammar-check, and so on. You must document the following:

    -   the version of the generative AI used

    -   the full sequence of prompts and responses

    -   any additional inputs you provided to the AI system

    -   a “diff” between the AI responses and your submission, showing exactly what was generated by the AI system and what you changed.

It may be useful to leverage AI tools to ensure that your work conforms to grammar and style guidelines, but I very highly discourage the use of generative AI for content or code (I've seen it generate incorrect code too many times).

-   You must be able to explain any work you turn in, including code. If you cannot explain the logic behind your approach as well as how it works in practice, then you will not receive credit for your submission.

**Department Grade Appeal Policy:** The Department of Statistics [grade appeal policy](https://statistics.unl.edu/department-policies-grade-appeals-academic-integrity/)

**Academic Integrity:** You are encouraged to work together on problems and exercises, but the work you turn in must be your own (unless the assignment specifically states otherwise). Work on exams must be your own. University policy will be followed in cases of academic dishonesty: In cases where an instructor finds that a student has committed any act of academic dishonesty, the instructor may in the exercise of his or her professional judgment impose an academic sanction as severe as giving the student a failing grade in the course. Before imposing an academic sanction the instructor shall first attempt to discuss the matter with the student. If deemed necessary by either the instructor or the student, the matter may be brought to the attention of the student's major advisor, the instructor's department chairperson or head, or the dean of the college in which the student is enrolled. For additional details see [the department policy.](https://statistics.unl.edu/department-policies-grade-appeals-academic-integrity/)

**Services for Students with Disabilities:** The University strives to make all learning experiences as accessible as possible. If you anticipate or experience barriers based on your disability (including mental health, chronic or temporary medical conditions), please let your instructor know immediately so that you can discuss options privately. To establish reasonable accommodations, your instructor may request that you register with Services for Students with Disabilities. If you are eligible for services and register with the office, make arrangements with your instructor as soon as possible to discuss your accommodations so they can be implemented in a timely manner. SSD is located in 117 Louise Pound Hall and can be reached at 402-472-3787.

**University Policies:** All [university-wide course policies.](https://executivevc.unl.edu/academic-excellence/teaching-resources/course-policies/)

\newpage

[***TENTATIVE***]{.underline} **Course Outline**

| Week | Dates | Notes | Topics |
|----|----|----|----|
| 1 | 13-15 January |  | Introduction; probability basics; counting; conditional probability |
| 2 | 20-22 January | HW 1 due | Conditional probability; Bayes' theorem; independence; RVs; CDFs |
| 3 | 27-29 January | HW 2 due | pdfs/pmfs; expected values; moments |
| 4 | 3-5 February | HW 3 due | Moments; mgfs |
| 5 | 10-12 February | HW 4 due | Kernels; quantities based on moments; discrete distributions |
| 6 | 17-19 February |  | **Exam 1** |
| 7 | 24-26 February |  | Discrete distributions; continuous distributions |
| 8 | 3-5 March | HW 5 due | Multiple RVs; marginals; independence |
| 9 | 10-12 March | HW 6 due | Conditional distributions; conditional expectations; covariance; correlation |
| 10 | 17-19 March | No class! | Spring Break |
| 11 | 24-26 March | HW 7 due | Multiple RVs revisited; named multivariate distributions; transformations |
| 12 | 31 March - 2 April | HW 8 due | Transformations; multivariate mgfs |
| 13 | 7-9 April |  | **Exam 2** |
| 14 | 14-16 April |  | Random samples; sampling from a normal distribution |
| 15 | 21-23 April | HW 9 due | Convergence; CLT |
| 16 | 28-30 April |  | **Final project presentations** |
| Finals Week |  | No final exam | **Final project papers due Monday, 4 May at 9:00 am** |
